# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main            # rama que dispara la pipeline

# pool raíz ⇒ valor por omisión para todos los jobs
pool:
  name: SelfHostedAgentPools

# ───────── variables globales del pipeline ─────────


# ───────────────────────────────────────────
#  JOB 1  ·  TEST
# ───────────────────────────────────────────
jobs:
  # ── Job 1 ─ Test ───────────────────────────
  - job: Test
    displayName: "Build & Run Tests"
    steps:

      # 1 Ejecuta las pruebas (Cloud = BrowserStack)
      - script: 'gradlew clean cloud'
        displayName: 'Run Tests'
      #  continueOnError: true          # deja seguir al job aunque las pruebas fallen

  # ── Job 2 ─ Azure CLI ───────────────────────────
  - job: Azure
    dependsOn: Test
    condition: always()
    steps:
      # Agregar ruta de Azure CLI en las variables de entorno del agente
      - powershell: '$env:Path += ";C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin"'
        displayName: 'Path Azure CLI'

  # ── Job 3 ─ Report ───────────────────────────
  - job: Reporte
    dependsOn: Azure
    condition: always()
    steps:
      # 2 Genera el reporte HTML/JSON
      - script: 'gradlew report'
        displayName: 'Generate Report'

      # 3 Copia SOLO el reporte (no todo el repo)
      - task: CopyFiles@2
        displayName: 'Copy Cucumber Report to Staging'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/*'
          TargetFolder: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()

      # 4 Publica el artefacto de reporte
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: FlexBusiness Mobile'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: FlexBusinessMobileTest
        condition: succeededOrFailed()

      # 5 Obtiene la storagekey ─ (opcional: solo si sigues usando blob estático)
      - task: AzureCLI@2
        displayName: 'Obtener clave de acceso a la cuenta de almacenamiento'
        inputs:
          azureSubscription: 'AzureResourceManagerServicePrincipalManual'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            $storageAccountKey = az storage account keys list `
              --resource-group rg-qa-001 `
              --account-name  storageqa001 `
              --query '[0].value' --output tsv
            echo "##vso[task.setvariable variable=StorageAccountKey;issecret=true]$storageAccountKey"
        condition: succeededOrFailed()

      # 6 Sube el reporte al sitio estático (opcional)
      - task: AzureCLI@2
        displayName: 'Cargar los archivos de cucumber-report al contenedor'
        inputs:
          azureSubscription: 'AzureResourceManagerServicePrincipalManual'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob upload-batch `
              --account-name storageqa001 `
              --account-key  $(StorageAccountKey) `
              --destination  '$web' `
              --source       reports/FlexBusinessMobile/cucumber-html-reports `
              --type block
        condition: succeededOrFailed()

  # ───────────────────────────────────────────
  #  JOB 4  ·  COLLECTOR  (solo si Test falló)
  # ───────────────────────────────────────────
  - job: Collector
    displayName: "Collector Job"
    dependsOn: Reporte
    condition: failed('Test')
    pool: { name: SelfHostedAgentPools }

    steps:
      # 1) Descarga el artefacto publicado en el job Test
      - download: current
        artifact: FlexBusinessMobileTest          # ← nombre exacto del artifact

      # 2) Copia el directorio cucumber‑html‑reports + report.json
      - powershell: |
          Write-Host "Empaquetando artefactos de fallos…"
          
          # Ruta raíz del artifact descargado
          $artifactRoot = "$(Pipeline.Workspace)\FlexBusinessMobileTest"
          
          # Destino local (será publicado luego)
          $dest = "$(System.DefaultWorkingDirectory)\artifacts"
          New-Item -Path $dest -ItemType Directory -Force | Out-Null
          
          # Directorio HTML
          $reportDir = Join-Path $artifactRoot "reports\FlexBusinessMobile\cucumber-html-reports"
          if (Test-Path $reportDir) {
              Copy-Item -Recurse -Force $reportDir $dest
              Write-Host "Copiado $reportDir"
          } else {
              Write-Warning "No se encontró $reportDir"
          }
          
          # JSON (si existe)
          $json = Join-Path $artifactRoot "reports\report.json"
          if (Test-Path $json) {
              Copy-Item -Force $json $dest
              Write-Host "Copiado $json"
          } else {
              Write-Warning "report.json no encontrado"
          }
        displayName: "Copiar reportes fallidos"

      # 3) Publica los archivos para QA‑Copilot
      - task: PublishBuildArtifacts@1
        displayName: "Publicar FailArtifacts"
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)\artifacts'
          artifactName: FailArtifacts

  # ── JOB · INSTALL PYTHON ────────────────────────────────────────────────
  - job: InstallPython
    displayName: "Ensure Python 3.13 is present"
    dependsOn: Collector
    condition: always()
    pool: { name: SelfHostedAgentPools }

    steps:
      - powershell: |
          # 1) ¿Python 3.13+ ya está en PATH?
          $pythonExe = (& where.exe python.exe 2>$null) -split "`r?`n" | Select-Object -First 1
          if ($pythonExe) {
              $ver = & $pythonExe --version
              if ($ver -match 'Python 3\.(1[1-9]|[2-9]\d)') {
                  Write-Host "Python ya instalado: $ver – omitimos instalación."
                  exit 0
              }
          }
          
          Write-Host "Python 3.13 no encontrado. Procediendo a instalar…"
          
          # 2) Descargar el instalador
          $url       = "https://www.python.org/ftp/python/3.13.3/python-3.13.3-amd64.exe"
          $installer = "$env:TEMP\python-3.13.3-amd64.exe"
          Invoke-WebRequest -Uri $url -OutFile $installer
          
          # 3) Instalar en modo silencioso
          Start-Process -FilePath $installer `
                        -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" `
                        -Wait
          
          # 4) Localizar python.exe tras la instalación
          Write-Host "Buscando python.exe en PATH…"
          $pythonExe = (& where.exe python.exe 2>$null) -split "`r?`n" | Select-Object -First 1
          
          if (-not $pythonExe) {
              Write-Host "No hallado en PATH, buscando en Program Files…"
              $candidate = Get-ChildItem "$Env:ProgramFiles" -Directory -Filter "Python313*" |
                           Sort-Object LastWriteTime -Descending |
                           Select-Object -First 1
              if ($candidate) { $pythonExe = "$($candidate.FullName)\python.exe" }
          }
          
          if ($pythonExe -and (Test-Path $pythonExe)) {
              # 5) Actualizar PATH de esta sesión
              $pythonDir = Split-Path $pythonExe -Parent
              $env:PATH = "$pythonDir;$pythonDir\Scripts;"+$env:PATH
              Write-Host "python.exe localizado en $pythonExe"
              Write-Host "Versión instalada: $(& $pythonExe --version)"
              exit 0
          } else {
              Write-Warning "python.exe NO encontrado tras la instalación."
              exit 1
          }
        displayName: "Check, Install & Locate Python 3.13+"


  # ───────────────────────────────────────────
  #  JOB 5  ·  QA‑COPILOT  (IA RCA + PDF)
  # ───────────────────────────────────────────
  - job: QA_Copilot
    displayName: "AI Root‑Cause & Executive Report"
    dependsOn: InstallPython
    condition: succeeded('Collector')      # Collector debe haber ido OK
    pool: { name: SelfHostedAgentPools }

    steps:
      # 1) Descarga el artefacto con los reportes fallidos
      - download: current
        artifact: FailArtifacts

      # 2) Instala dependencias Python y genera el markdown
      - powershell: |
          python -m pip install --upgrade pip
          pip install openai weasyprint requests   # depende de tus scripts
          
          $cucumber = "$(Pipeline.Workspace)\FailArtifacts\reports\report.json"
          $logs     = "$(Pipeline.Workspace)\FailArtifacts\logs"
          
          Write‑Host "Generando rca.md con GPT‑4o…"
          python scripts/generate_rca.py `
                 --cucumber $cucumber `
                 --logs     $logs `
                 --output   rca.md
        displayName: "Generar RCA (markdown)"
        env:
          OPENAI_API_KEY: $(OPENAI_API_KEY)

      # 3) Convertir a PDF
      - powershell: weasyprint rca.md rca.pdf
        displayName: "Convertir md → PDF"

      # 4) Publicar el PDF
      - task: PublishBuildArtifacts@1
        displayName: "Publicar RCA_Report"
        inputs:
          PathtoPublish: 'rca.pdf'
          ArtifactName: RCA_Report

      # 5) Comentar el Pull Request
      - powershell: |
          python scripts/post_to_ado.py `
                 --pr $(System.PullRequest.PullRequestId) `
                 --file rca.md
        displayName: "Comentar RCA en PR"
        env:
          ADO_PAT: $(ADO_PAT)