# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main  # Puedes ajustar la rama desencadenante según tu configuración

pool:
  name: PortafolioAG  # Puedes ajustar la imagen de la máquina según tus necesidades

steps:
  - script: 'gradlew clean cloud'
    displayName: 'Run Test'
    continueOnError: true

  - script: 'gradlew report'
    displayName: 'Generate Report'

  - powershell: '$env:Path += ";C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin"'
    displayName: 'Path Azure CLI'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: FlexBusiness Mobile'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: FlexBusinessMobileTest
    condition: succeededOrFailed()

  - task: AzureCLI@2
    displayName: 'Obtener clave de acceso a la cuenta de almacenamiento'
    inputs:
      azureSubscription: 'AzureResourceManager'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $storageAccountKey = az storage account keys list --resource-group GR-QA --account-name appiumtestreport --query '[0].value' --output tsv
        echo "##vso[task.setvariable variable=StorageAccountKey]$storageAccountKey"

  - task: AzureCLI@2
    displayName: 'Cargar los archivos de cucumber-report al contenedor'
    inputs:
      azureSubscription: 'AzureResourceManager'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload-batch --account-name appiumtestreport --account-key $(StorageAccountKey) --destination '$web' --source reports/cucumber/FlexBusinessMobile/cucumber-html-reports --type block